version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: x64
clone_depth: 1
before_build:
- cmd: git submodule update --init --recursive
build:
  project: src\CE.sln
  parallel: true
  verbosity: minimal
test: off
deploy: off